import mongoose from 'mongoose'

const userSchema = new mongoose.Schema({
  id: { type: String, required: true },
  username: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  image: String,
  bio: String,
  threads: [
    {
      type: mongoose.Schema.Types.ObjectId, // ObjectId is a unique identifier automatically generated by MongoDB for each document.
      ref: 'Thread'
    }
  ],
  onboarded: {
    type: Boolean,
    default: false
  },
  communities: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Community' // specifies the Mongoose model to which the ObjectId refers. In this case, it refers to the 'Community' model.
    }
  ]
})

const User = mongoose.models.User || mongoose.model('User', userSchema)

export default User
